apiVersion: batch/v1
kind: Job
metadata:
  name: fail-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fail
        image: busybox
        command: ["sh", "-c", "exit 1"]
